# Generated by Django 5.0.4 on 2024-05-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='info_link',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention',
            field=models.TextField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='treatments',
            field=models.TextField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
