# Generated by Django 5.0.4 on 2024-05-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_disease_info_link_disease_prevention_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='info_link',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='prevention',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='treatments',
        ),
    ]
